### ISSUE TITLE
Cannot change colors

### ISSUE THREAD

**Issue by 7200rpm** [TouPye/angular-circular-progress#1]
Can't seem to change either the baseColor or progressColor. Opened the demo and changed the colors and still red/gray. I was able to change the colors by editing the JS file, but not from the index.html directives.

**Comment by pistou** [comment]
Ok I found the issue.
I updated the doc.

Instead of using `baseColor` or `progressColor` attributes in your HTML, use `base-color` and `progress-color`

**Comment by 7200rpm** [comment]
Thanks for the quick fix!
